batch_size: 16
config: null
config_path: null
crop_strategy: e2p
csv_train: data/quic360/train.csv
csv_val: data/quic360/valid.csv
eval_mode: false
image_size:
- 224
- 224
lm_name: Qwen/Qwen2.5-0.5B-Instruct
lora_alpha: 64
lora_dropout: 0.1
lora_rank: 32
lora_target_modules:
- q_proj
- k_proj
- v_proj
- o_proj
- gate_proj
- up_proj
- down_proj
lr: 4.0e-05
max_text_length: 32
num_workers: 16
overlap_ratio: 0.5
resampler: mlp
stage: vision
system_msg: null
tokenizer_name: Qwen/Qwen2.5-0.5B-Instruct
use_lora: true
vicreg_loss_weight: 1.0
vision_name: google/siglip-base-patch16-224
