
# =============================================================================
# PanoLLaVA Model Configuration 
# 실제 코드에서 사용되는 설정들만 포함
# =============================================================================

# 모델 설정 - 실제 사용되는 모델들
model:
  # Vision encoder (실제 사용: SigLIP)
  vision_model_name: "google/siglip-base-patch16-224"
  
  # Language model (실제 사용: Qwen)  
  language_model_name: "Qwen/Qwen2-0.5B"
  
  # Resampler 타입
  resampler_type: "mlp"  # mlp, spatial_pool, masked_drop
  
  # LoRA 설정
  lora:
    enabled: false
    r: 16
    alpha: 32
    dropout: 0.1

# 데이터 설정
data:
  # CSV 파일 경로 (명령행에서 오버라이드 가능)
  csv_train: "./data/train.csv"
  csv_val: "./data/val.csv"
  
  # 배치 설정
  batch_size: 4
  num_workers: 4
  
  # 텍스트 설정
  max_text_length: 512
  tokenizer_name: "Qwen/Qwen2-0.5B"
  
  # 이미지 설정 - 실제 사용되는 옵션들
  image:
    size: [224, 224]
    crop_strategy: "e2p"  # e2p, sliding_window, cubemap

# 학습 설정
training:
  learning_rate: 1e-4
  epochs: 3
  gradient_clip_val: 1.0

# VICReg 손실 설정 (Stage 1에서 사용)
vicreg:
  loss_weight: 1.0

# 검증 설정
validation:
  check_interval: 0.5  # 에포크의 50%마다 검증

# 하드웨어 설정
hardware:
  accelerator: "auto"
  devices: "auto"
  precision: "16-mixed"
  deterministic: false
  benchmark: true

# 로깅 설정
logging:
  wandb:
    project: "panorama-vlm"
    name: null  # 자동 생성
    dir: "./wandb_logs"
