# =============================================================================
# Stage 2: Resampler Training Configuration  
# Resampler 모듈 학습
# =============================================================================

# 기본 설정 상속
base_config: "model_config.yaml"

# Stage 2 특화 설정
training:
  learning_rate: 1e-4
  epochs: 1
  gradient_clip_val: 1.0

# 모델 프리징 설정
model:
  freeze_vision_encoder: true
  freeze_language_model: true

# 로깅
logging:
  wandb:
    name: "resampler_stage"
