# 학습 설정
training:
  # 기본 학습 파라미터
  batch_size: 8
  learning_rate: 1e-4
  weight_decay: 0.01
  num_epochs: 10
  
  # 학습 스케줄러
  scheduler:
    type: "cosine"  # "linear", "cosine", "polynomial"
    warmup_steps: 1000
    min_lr: 1e-6
  
  # 옵티마이저
  optimizer:
    type: "adamw"  # "adam", "adamw", "sgd"
    beta1: 0.9
    beta2: 0.999
    epsilon: 1e-8
  
  # 그래디언트 설정
  gradient_clipping: 1.0
  accumulation_steps: 4
  
  # 정규화
  dropout: 0.1
  label_smoothing: 0.1

# 데이터 설정
data:
  # 데이터 경로
  train_data_path: "data/train"
  val_data_path: "data/val" 
  test_data_path: "data/test"
  
  # 데이터 로더 설정
  num_workers: 4
  pin_memory: true
  persistent_workers: true
  
  # 데이터 증강
  augmentation:
    enabled: true
    probability: 0.5
    
    # 이미지 증강
    image_aug:
      rotation: 10
      brightness: 0.2
      contrast: 0.2
      saturation: 0.2
      hue: 0.1
    
    # 텍스트 증강  
    text_aug:
      synonym_replacement: 0.1
      random_insertion: 0.1
      random_swap: 0.1
      random_deletion: 0.1

# 검증 설정
validation:
  eval_steps: 500
  eval_batch_size: 16
  save_best_model: true
  patience: 3  # Early stopping
  
  # 평가 메트릭
  metrics:
    - "bleu"
    - "rouge"
    - "cider"
    - "accuracy"

# 체크포인트 및 로깅
checkpoint:
  save_dir: "checkpoints"
  save_steps: 1000
  save_total_limit: 3
  load_best_model_at_end: true
  
  # 모델 저장 설정
  save_strategy: "steps"  # "steps", "epoch", "no"
  evaluation_strategy: "steps"

# 로깅 설정
logging:
  output_dir: "logs"
  logging_steps: 100
  
  # Wandb 설정
  wandb:
    enabled: true
    project: "panollava"
    entity: "your-team"
    name: "experiment-1"
    tags: ["panorama", "multimodal", "llava"]
  
  # TensorBoard 설정
  tensorboard:
    enabled: true
    log_dir: "logs/tensorboard"

# 분산 학습 설정
distributed:
  enabled: false
  backend: "nccl"  # "nccl", "gloo"
  world_size: 1
  rank: 0
  
  # DeepSpeed 설정 (선택사항)
  deepspeed:
    enabled: false
    config_file: "config/deepspeed_config.json"

# 하드웨어 설정
hardware:
  # GPU 설정
  gpu:
    mixed_precision: true
    gradient_checkpointing: true
    dataloader_pin_memory: true
  
  # CPU 설정
  cpu:
    num_threads: 8
    
# 실험 설정
experiment:
  name: "panollava_baseline"
  description: "PanoLLaVA 기본 학습 실험"
  tags: ["baseline", "panorama", "multimodal"]
  
  # 재현성
  seed: 42
  deterministic: true
