# =============================================================================
# Stage 1: Vision Training Configuration
# VICReg loss를 사용한 비전 인코더 학습
# =============================================================================

# 기본 설정 상속
base_config: "model_config.yaml"

# Stage 1 특화 설정
training:
  learning_rate: 1e-4
  epochs: 3
  gradient_clip_val: 1.0

# VICReg 손실 설정  
vicreg:
  loss_weight: 1.0

# 모델 프리징 설정
model:
  freeze_language_model: true
  freeze_resampler: true

# 로깅
logging:
  wandb:
    name: "vision_stage"
