# ============================================================================
# 리샘플러 설정 예시
# ============================================================================

# 방법 1: resampler_type만 지정하면 자동으로 기본값 적용
models:
  resampler_type: mlp
  # MLPResamplerConfig가 자동 생성:
  # - latent_dimension: 768
  # - hidden_dim: 1536
  # - depth: 3
  # - use_ln: True
  # - dropout: 0.1
  # - num_views: 8

---
# 방법 2: resampler_config에 커스텀 값 지정
models:
  resampler_type: mlp
  resampler_config:
    latent_dimension: 1024
    hidden_dim: 2048
    depth: 4
    use_ln: True
    dropout: 0.2
    num_views: 8

---
# 방법 3: Perceiver 리샘플러 사용
models:
  resampler_type: perceiver
  resampler_config:
    latent_dimension: 768
    num_latents: 64      # Perceiver 전용
    heads: 16            # Perceiver 전용
    depth: 3
    use_ln: True
    dropout: 0.1
    num_views: 8

---
# 방법 4: BiMamba 리샘플러 사용
models:
  resampler_type: bimamba
  resampler_config:
    latent_dimension: 768
    hidden_dim: 1536
    enable_cross_view: True  # BiMamba 전용
    depth: 2
    use_ln: True
    dropout: 0.1
    num_views: 8

---
# 방법 5: Legacy 방식 (하위 호환성)
# 개별 필드를 직접 지정하면 자동으로 resampler_config 생성됨
models:
  resampler_type: mlp
  latent_dimension: 768
  resampler_depth: 3
  resampler_hidden_dim: 1536
  resampler_use_ln: True
  resampler_dropout: 0.1
  resampler_num_views: 8
