# Stage 2: Resampler Training with Vision Encoder
# ===============================================

stage: "resampler"

# 모델 설정 오버라이드
model:
  # LoRA는 resampler stage에서 사용하지 않음
  lora:
    enabled: false

# 학습 설정 - Resampler stage 최적화
training:
  epochs: 4
  learning_rate: 5e-5  # Resampler는 중간 학습률
  optimizer: "adamw"
  weight_decay: 0.05
  warmup_ratio: 0.15
  
  scheduler:
    type: "linear_with_warmup"
    warmup_steps: null

# VICReg + AR Loss 혼합
vicreg:
  loss_weight: 0.5  # Resampler stage에서는 VICReg 가중치 감소
  similarity_weight: 25.0
  variance_weight: 25.0
  covariance_weight: 1.0

# 데이터 설정
data:
  batch_size: 6
  num_workers: 6
  max_txt_len: 64  # Resampler stage에서는 중간 길이

# 로깅 설정
logging:
  wandb:
    name: "resampler-stage"
  
  early_stopping:
    patience: 3
    min_delta: 0.005

# 검증 설정
validation:
  check_interval: 0.25  # 더 빈번한 검증
  log_samples: true     # Resampler stage부터 생성 샘플 로깅
  num_samples: 3
  max_new_tokens: 24
  temperature: 0.8

# 하드웨어 설정
hardware:
  precision: "16-mixed"