# Stage 1: Vision Encoder Training with VICReg Loss
# ==================================================

# base.yaml 설정을 상속받고 stage별 override
stage: "vision"

# 모델 설정 오버라이드
model:
  # LoRA는 vision stage에서 사용하지 않음
  lora:
    enabled: false

# 학습 설정 - Vision stage 최적화
training:
  epochs: 3
  learning_rate: 2e-5  # Vision encoder는 상대적으로 높은 학습률
  optimizer: "adamw"
  weight_decay: 0.01
  warmup_ratio: 0.2    # 20% warmup for vision training
  
  # Vision stage는 더 긴 warmup 필요
  scheduler:
    type: "cosine_with_warmup"
    warmup_steps: null

# VICReg Loss 설정 - Vision stage에서 중요
vicreg:
  loss_weight: 1.0
  similarity_weight: 25.0
  variance_weight: 25.0
  covariance_weight: 1.0

# 데이터 설정
data:
  batch_size: 4      # Vision stage는 더 큰 배치 사이즈 가능
  num_workers: 8
  max_txt_len: 32   # Vision stage에서는 텍스트 길이 작게

# 로깅 설정
logging:
  wandb:
    name: "vision-stage"
  
  # Vision stage는 빠른 수렴 가능
  early_stopping:
    patience: 2
    min_delta: 0.01

# 검증 설정
validation:
  check_interval: 0.5  # Vision stage는 덜 빈번한 검증
  log_samples: false   # Vision stage에서는 생성 샘플 로깅 불필요

# 하드웨어 설정
hardware:
  precision: "16-mixed"  # Vision encoder는 mixed precision 안전